stages:
  - publish
  - deploy_staging

publish:
  image: docker:19.03.0
  stage: publish
  services:
    - docker:19.03.0-dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/$CI_DEPLOY_USER/$CI_PROJECT_NAME:$CI_COMMIT_SHA -f Dockerfile .
    - docker push $CI_REGISTRY/$CI_DEPLOY_USER/$CI_PROJECT_NAME:$CI_COMMIT_SHA

deploy_staging:
  image: docker:19.03.0
  stage: deploy_staging
  only:
    - staging
  variables:
    DOCKER_HOST: "tcp://meetyourtutor.online:2376"
    DOCKER_CERT_PATH: "certs"
    DOCKER_TLS_VERIFY: "1"
  before_script:
    - mkdir $DOCKER_CERT_PATH
    - echo "$TLSCACERT" > $DOCKER_CERT_PATH/ca.pem
    - echo "$TLSCERT" > $DOCKER_CERT_PATH/cert.pem
    - echo "$TLSKEY" > $DOCKER_CERT_PATH/key.pem
  script:
    - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY
    - docker stack deploy --with-registry-auth -c stack.yml meet_your_tutor_front
  dependencies:
    - publish
