version: '3.7'

services:
  app:
    image: "$CI_REGISTRY/$CI_DEPLOY_USER/$CI_PROJECT_NAME:$CI_COMMIT_SHA"
    networks:
      - traefik-public
    volumes:
      - '/app/node_modules'
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.app.rule=Host(`meetyourtutor.online`)"
        - "traefik.http.services.app.loadbalancer.server.port=6000"
        - "traefik.http.routers.app.entrypoints=websecure"
        - "traefik.http.routers.app.tls.certresolver=leresolver"

volumes:
  db-data:

networks:
  traefik-public:
    external: true